name: Publish
on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  build-linux:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
        - name: Linux
          os: ubuntu-latest
        - name: Windows
          os: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: "9.4.8"
        cabal-version: "3.10.3.0"
    - name: Install dependencies
      if: runner.os == 'Windows'
      run: |
        choco install upx
    - name: Build
      run: |
        zig build-exe src/main.zig --name maid
    - name: Publish
      if: runner.os == 'Linux'
      run: |
        pkg=maid-$(./maid -q version)
        ./maid install --dstdir=$pkg
        tar --remove-files -cf "$pkg.tar.gz" "$pkg"

        gh release upload "$GITHUB_REF_NAME" "$pkg.tar.gz"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      if: runner.os == 'Windows'
      run: |
        exe=maid-$(./maid.exe -q version).exe
        cp "$binpath" "$exe"
        strip "$exe" && upx "$exe"
        gh release upload "$GITHUB_REF_NAME" "$exe"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
