name: Publish
on:
  workflow_dispatch:
  release:
    types: [published, edited]

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  build-linux:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
        - name: Linux
          os: ubuntu-latest
        - name: Windows
          os: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.4.8'
        cabal-version: '3.10'

    - name: Build
      run: |
        cp cabal.project.{release,local}
        cabal update
        cabal build --enable-static
        echo "binpath=$(cabal list-bin maid)" >> $GITHUB_ENV
    - name: Publish
      if: runner.os == 'Linux'
      run: |
        pkg=maid-$("$binpath" -q version)
        dstdir=$pkg "$binpath" install
        tar --remove-files -cf "$pkg.tar.gz" "$pkg"

        gh release upload "$GITHUB_REF_NAME" "$pkg.tar.gz"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      if: runner.os == 'Windows'
      run: |
        exe=maid-$("$binpath" -q version).exe
        cp "$binpath" "$exe"
        gh release upload "$GITHUB_REF_NAME" "$exe"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
