name: Publish
on:
  workflow_dispatch:
  release:
    types: [published, edited]

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  build-linux:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
        - name: Linux
          os: ubuntu-latest
        - name: Windows
          os: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.4.8'
        cabal-version: '3.10'

    - name: Build
      run: |
        cabal update
        cabal build --enable-static --project-file=cabal.project.release
        echo "binpath=$(cabal list-bin --project-file=cabal.project.release maid)" >> $GITHUB_ENV
    - name: Publish
      if: runner.os == 'Linux'
      run: |
        gh release upload "$GITHUB_REF_NAME" "${{env.binpath}}#maid-$GITHUB_REF_NAME-x86_64-linux"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      if: runner.os == 'Windows'
      run: |
        gh release upload "$GITHUB_REF_NAME" "${{env.binpath}}#maid-$GITHUB_REF_NAME-x86_64-windows.exe"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
