name: Publish
on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  build-linux:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
        - name: Linux
          os: ubuntu-latest
        - name: Windows
          os: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@v3
      with:
        version: 0.14.0-dev.2563+af5e73172

    - name: Build
      run: zig build-exe src/main.zig --name maid

    - name: Publish
      if: runner.os == 'Linux'
      run: |
        pkg=maid-$(./maid -q version).tar.gz
        ./maid install --dstdir=package
        tar --remove-files -cf "$pkg" package

        gh release upload "$GITHUB_REF_NAME" "$pkg"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish
      if: runner.os == 'Windows'
      run: |
        exe=maid-$(./maid.exe -q version).exe
        cp maid.exe "$exe"
        gh release upload "$GITHUB_REF_NAME" "$exe"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
