name: Build and test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  build-linux:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
        - name: Linux
          os: ubuntu-latest
        - name: Windows
          os: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: mlugg/setup-zig@v3
      with:
        version: 0.14.0-dev.2563+af5e73172

    - name: Build
      run: zig build-exe src/main.zig --name maid
